# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 18:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='tiempo',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 26, 18, 7, 33, 417000, tzinfo=utc)),
        ),
    ]
